fails:Exception.new creates a new instance of Exception
fails:Exception.new sets the message of the Exception when passes a message
fails:Exception.new returns 'Exception' for message when no message given
fails:Exception.new returns the exception when it has a custom constructor
